
services:
  agent-backend:
    build:
      context: ./agent_backend
      dockerfile: Dockerfile
    container_name: agent-backend
    env_file:
        - ./agent_backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./agent_backend/src:/app
    depends_on:
      - notes-backend
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  notes-backend:
    build:
      context: ./notes_backend
      dockerfile: Dockerfile
    container_name: notes-backend
    env_file:
        - ./notes_backend/.env
    ports:
      - "8001:8001"
    volumes:
      - ./notes_backend/src:/app
    depends_on:
      - db

  db:
    image: postgres:15.10
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1421
      POSTGRES_DB: note_db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  db-test:
    image: postgres:15.6
    container_name: postgres_test
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=note_test
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9090:8080"

volumes:
  postgres-db:
    driver: local
